### ISSUE TITLE
Understanding the cache mechanism

### ISSUE THREAD

**Issue by apehead** [module-federation/node#11]
Hi @ScriptedAlchemy 

Thanks for sharing this valuable plugin :slightly_smiling_face: 

After playing a bit with the plugin and checking the source code, I would like to better understand how the current cache mechanism works and how to adapt it to other scenarios when needed.

With the current approach, when running a server (host app), the remote modules are only fetched once, the first time they are needed, and I guess this behavior is intended. But this also means that when the remotes change, the server will not fetch the changes again and you need to restart the server to be updated.

This behavior is easy to reproduce with [this example](https://github.com/module-federation/module-federation-examples/tree/master/server-side-rendering).

I have been experiencing the following issues:

1. When developing an SSR app with React and updating a remote module, server-side rendered code gets outdated and doesn't match the client code. Therefore you get the warnings plus a flash of mismatched content. Also, the server app supports HMR, so restarting the server is not ideal.
2. When running a server-side rendered app in production, the server doesn't know if a remote module has changed and returns outdated content with the corresponding negative effects. To keep the server code updated, you would need to restart it every time a remote module changes, which could be a complex process.

What's the best approach for these scenarios? Can I modify this behavior? 
Am I missing something here? :thinking: 

Thanks!

**Comment by ScriptedAlchemy** [comment]
You'd need to "hot reload" node. 

You can see a example in flushChunks under nextjs-ssr 

Basically reset require cache forcing webpack to restart and fetch chunks again

**Comment by apehead** [comment]
Thanks, I understand. I will give it a try.

Do you think this plugin should provide the `flushChunks` to be used as explained in the nextjs-ssr "Hot Reloadable Production Servers" section? That way, for example, `flushChunks` could be used in a middleware after every request.
But maybe you consider this is out of the scope of this project.

Mentioning @botoxparty as they could be interested in the topic after the work on https://github.com/module-federation/module-federation-examples/pull/2014

**Comment by botoxparty** [comment]
For question #2, See: https://github.com/module-federation/medusa. It's a dashboard that lets you visualize the relationships between your remotes. It works by running a server for the dashboard, and generates a file (dashboard.json) that should be sent to the server when a new remote is built. 

From there you would be able to know which remotes should be updated when changes are made. 

The repository seems to be unmaintained and maybe not production ready. Medusa is much more advanced now and has been made available as a service (https://www.medusa.codes/).

You could also just use the `DashboardPlugin` and then create your own dashboard server.

**Comment by apehead** [comment]
@ScriptedAlchemy I adapated the [revalidate function](https://github.com/module-federation/nextjs-ssr/blob/ca598943617f38bd5d391e28d8bb280b82e1cb1e/flushChunks.js#L275-L359) from nextjs-ssr but I'm not able to reset the cache at [this point](https://github.com/module-federation/nextjs-ssr/blob/ca598943617f38bd5d391e28d8bb280b82e1cb1e/flushChunks.js#L345-L354).

I checked every cache key, but none of them references the remote modules.

Are loaded chunks expected to be on the require cache?
Should I follow another approach to do the reset?

Thanks!

**Comment by ScriptedAlchemy** [comment]
Note medusa is SaaS only. The version that public is very old and likely no longer compatible with the plugin

**Comment by ScriptedAlchemy** [comment]
Do you use express? If you're using express you also need to reset the route stack as express caches all middleware in memory therefore caching the server render function

**Comment by ScriptedAlchemy** [comment]
Yes this is going to be implemented in nextjs-MF we have just been busy with moving to NX so SSR progress has been delayed

**Comment by ScriptedAlchemy** [comment]
revalidation pr is open under nextjs-mf/packages/node

**Comment by apehead** [comment]
> revalidation pr is open under nextjs-mf/packages/node

Awesome, thanks! I will follow up on the work there.
I think we could close this issue.

**Comment by ScriptedAlchemy** [comment]
Perfect
